

server:
  port: 8081

#�����Ȳ���
spring:
  devtools:
    restart:
      enabled: true  #���ÿ����Ȳ���
      additional-paths: src/main/java #����Ŀ¼
      exclude: WEB-INF/**
  freemarker:
    cache: false    #ҳ�治���ػ��棬�޸ļ�ʱ��Ч
  application:
    name: app
